version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.2.1

jobs:
  build:
    executor: aws-cli/default
    environment:
      PACKER_VERSION: '1.6.0'
    parameters:
      eks:
        description: "Which EKS version to build"
        default: "1.16"
        type: string
    working_directory: ~/repo
    steps:
      - checkout
      - aws-cli/setup:
          configure-default-region: true
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: Get packer binary
          command: |
            curl -o packer.zip https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
            unzip packer.zip
            sudo mv packer /usr/local/bin
      - run:
          name: Get AWS session manager plugin
          command: |
            curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
            sudo dpkg -i session-manager-plugin.deb
      - run:
          name: Build AMI
          command: make << parameters.eks >>

workflows:
  version: 2
  build_and_push:
    jobs:
    - build:
        context: global-production
        eks: "1.16"
        filters:
            branches:
              only: master
    - build:
        context: global-production
        eks: "1.17"
        filters:
            branches:
              only: master
